window.Card = class Card
  constructor: (options={}) ->
    @name = options['name']
    @kingdom = options['kingdom']
    @stars = options['stars']
    @wait = options['wait']
    @base_attack = options['base_attack']
    @attack_per_level = options['attack_per_level']
    @base_hp = options['base_hp']
    @hp_per_level = options['hp_per_level']
    @level_0_ability = options['level_0_ability']
    @level_5_ability = options['level_5_ability']
    @level_10_ability = options['level_10_ability']
    @level_15_ability = options['level_15_ability']